CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    phone VARCHAR(40) NOT NULL,
    email VARCHAR(254),
    notes VARCHAR(2000),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE TABLE materials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    price_per_kg NUMERIC(14, 2) NOT NULL,
    active BOOLEAN NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE TABLE printers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    model VARCHAR(100),
    cost_per_hour NUMERIC(14, 2) NOT NULL,
    active BOOLEAN NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE TABLE quotes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quote_number VARCHAR(30) NOT NULL UNIQUE,
    customer_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('DRAFT', 'SENT', 'ACCEPTED', 'REJECTED')),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    valid_until DATE NOT NULL,
    estimated_delivery_date DATE,
    deposit_percentage NUMERIC(7, 4),
    notes VARCHAR(3000),
    markup_percentage NUMERIC(7, 4) NOT NULL,
    discount_percentage NUMERIC(7, 4) NOT NULL,
    tax_enabled BOOLEAN NOT NULL,
    tax_percentage NUMERIC(7, 4) NOT NULL,
    internal_cost NUMERIC(16, 2) NOT NULL,
    suggested_subtotal NUMERIC(16, 2) NOT NULL,
    final_subtotal NUMERIC(16, 2) NOT NULL,
    discount_amount NUMERIC(16, 2) NOT NULL,
    tax_amount NUMERIC(16, 2) NOT NULL,
    total NUMERIC(16, 2) NOT NULL,
    estimated_profit NUMERIC(16, 2) NOT NULL,
    real_margin_percentage NUMERIC(10, 4) NOT NULL,
    CONSTRAINT fk_quotes_customer FOREIGN KEY (customer_id) REFERENCES customers (id)
);

CREATE TABLE quote_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quote_id BIGINT NOT NULL,
    name VARCHAR(200) NOT NULL,
    quantity INTEGER NOT NULL,
    material_id BIGINT NOT NULL,
    printer_id BIGINT NOT NULL,
    weight_grams NUMERIC(14, 3) NOT NULL,
    print_time_minutes INTEGER NOT NULL,
    failure_risk_percentage NUMERIC(7, 4) NOT NULL,
    material_price_per_kg_snapshot NUMERIC(14, 2) NOT NULL,
    printer_cost_per_hour_snapshot NUMERIC(14, 2) NOT NULL,
    material_cost_unit NUMERIC(14, 2) NOT NULL,
    machine_cost_unit NUMERIC(14, 2) NOT NULL,
    failure_risk_cost_unit NUMERIC(14, 2) NOT NULL,
    additional_charges_unit NUMERIC(14, 2) NOT NULL,
    internal_cost_unit NUMERIC(14, 2) NOT NULL,
    suggested_price_unit NUMERIC(14, 2) NOT NULL,
    manual_unit_price NUMERIC(14, 2),
    CONSTRAINT fk_quote_items_quote FOREIGN KEY (quote_id) REFERENCES quotes (id),
    CONSTRAINT fk_quote_items_material FOREIGN KEY (material_id) REFERENCES materials (id),
    CONSTRAINT fk_quote_items_printer FOREIGN KEY (printer_id) REFERENCES printers (id)
);

CREATE TABLE additional_charges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quote_item_id BIGINT NOT NULL,
    description VARCHAR(200) NOT NULL,
    amount NUMERIC(14, 2) NOT NULL,
    CONSTRAINT fk_additional_charges_item FOREIGN KEY (quote_item_id) REFERENCES quote_items (id)
);

CREATE INDEX idx_quotes_customer_id ON quotes (customer_id);
CREATE INDEX idx_quotes_created_at ON quotes (created_at DESC);
CREATE INDEX idx_quote_items_quote_id ON quote_items (quote_id);
CREATE INDEX idx_quote_items_material_id ON quote_items (material_id);
CREATE INDEX idx_quote_items_printer_id ON quote_items (printer_id);
CREATE INDEX idx_additional_charges_item_id ON additional_charges (quote_item_id);
