CREATE TABLE production_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quote_id BIGINT NOT NULL UNIQUE,
    order_number VARCHAR(40) NOT NULL UNIQUE,
    status VARCHAR(20) NOT NULL CHECK (status IN ('PENDING', 'IN_PRODUCTION', 'READY', 'DELIVERED', 'CANCELLED')),
    priority VARCHAR(10) NOT NULL CHECK (priority IN ('LOW', 'NORMAL', 'HIGH', 'URGENT')),
    due_date DATE,
    notes VARCHAR(3000),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    started_at TIMESTAMP(6) WITH TIME ZONE,
    ready_at TIMESTAMP(6) WITH TIME ZONE,
    delivered_at TIMESTAMP(6) WITH TIME ZONE,
    cancelled_at TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT fk_production_orders_quote FOREIGN KEY (quote_id) REFERENCES quotes (id)
);

CREATE TABLE production_order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    production_order_id BIGINT NOT NULL,
    quote_item_id BIGINT NOT NULL,
    name VARCHAR(200) NOT NULL,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    material_name VARCHAR(100) NOT NULL,
    printer_name VARCHAR(100) NOT NULL,
    printer_model VARCHAR(100),
    weight_grams NUMERIC(14, 3) NOT NULL CHECK (weight_grams >= 0),
    print_time_minutes INTEGER NOT NULL CHECK (print_time_minutes >= 0),
    assigned_printer_id BIGINT,
    completed_quantity INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL CHECK (status IN ('PENDING', 'IN_PROGRESS', 'COMPLETED', 'BLOCKED')),
    notes VARCHAR(2000),
    CONSTRAINT uq_production_item_quote_item UNIQUE (production_order_id, quote_item_id),
    CONSTRAINT chk_production_item_progress CHECK (
        completed_quantity >= 0
        AND completed_quantity <= quantity
        AND (status <> 'COMPLETED' OR completed_quantity = quantity)
        AND (status <> 'PENDING' OR completed_quantity = 0)
        AND (status = 'COMPLETED' OR completed_quantity < quantity)
    ),
    CONSTRAINT fk_production_items_order FOREIGN KEY (production_order_id) REFERENCES production_orders (id),
    CONSTRAINT fk_production_items_quote_item FOREIGN KEY (quote_item_id) REFERENCES quote_items (id),
    CONSTRAINT fk_production_items_printer FOREIGN KEY (assigned_printer_id) REFERENCES printers (id)
);

CREATE INDEX idx_production_orders_due_status ON production_orders (due_date, status);
CREATE INDEX idx_production_orders_created_at ON production_orders (created_at DESC);
CREATE INDEX idx_production_items_order ON production_order_items (production_order_id);
CREATE INDEX idx_production_items_printer ON production_order_items (assigned_printer_id);
