CREATE TABLE app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(80) NOT NULL,
    password_hash VARCHAR(60) NOT NULL,
    display_name VARCHAR(120) NOT NULL,
    role VARCHAR(20) NOT NULL,
    active BOOLEAN NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_app_users_username UNIQUE (username),
    CONSTRAINT chk_app_users_username_normalized CHECK (username = LOWER(BTRIM(username)) AND username <> ''),
    CONSTRAINT chk_app_users_display_name_not_blank CHECK (BTRIM(display_name) <> ''),
    CONSTRAINT chk_app_users_role CHECK (role IN ('ADMIN', 'OPERATOR'))
);

CREATE INDEX idx_app_users_active_role ON app_users (active, role);
